---
- hosts: nucs
  user: ncowen
  become: yes

  tasks:
  - name: Let IPTables See Bridged Traffic
    shell: |
      modprobe br_netfilter

  - name: Ensure netbridge.bridge-nf-call-iptables is set to 1
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
      br_netfilter
      EOF

  - name: Ensure netbridge.bridge-nf-call-iptables is set to 1
    shell: |
      cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF

  - name: Restart Sysctl
    shell: |
      sysctl --system


  - name: Install DNF Packages for K8s
    shell: |
      dnf -y install iproute-tc git htop
