---
- hosts: k8master
  user: ncowen
  become: yes

  tasks:
    
  - name: Add Firewall Rules to FirewallD to Master
    shell: |
      firewall-cmd --permanent --zone=public --add-port=6443/tcp
      firewall-cmd --permanent --zone=public --add-port=2379/tcp 
      firewall-cmd --permanent --zone=public --add-port=2380/tcp 
      firewall-cmd --permanent --zone=public --add-port=10250/tcp 
      firewall-cmd --permanent --zone=public --add-port=10251/tcp 
      firewall-cmd --permanent --zone=public --add-port=10252/tcp 
      firewall-cmd --reload
    